defaults:
  - benchmark: null
  - scheduler: null
  - optimizer: null
  - model: null
  - strategy: method_defaults.yaml
  - evaluation: evaluation.yaml
  - deploy: default.yaml
  - experiment: split_cifar10.yaml
  - hydra.yaml
